### ISSUE TITLE
INTEL_PL1_ENABLE_BITS_HIGH is never set?

### ISSUE THREAD

**Issue by Betaminos** [horshack-dpreview/setPL#2]
Hello there,

thank you for this nice script!
I have fiddled around a bit, to implement a read-only mode on my end and have come across what seems like a bug.
The script uses a variable called INTEL_PL1_ENABLE_BITS_HIGH in [line 252](https://github.com/horshack-dpreview/setPL/blob/0713c5ca18a44fe91971f3ff5071f220a0d91b91/setPL.sh#L252) but this variable is never set.
My guess is that this was supposed to be INTEL_**PL2**_ENABLE_BITS_HIGH which is set alongside INTEL_PL1_ENABLE_BITS_LOW early in the script.

**Comment by Betaminos** [comment]
I have tried solving this on my end, creating my very first pull request in the process :laughing: 
Let's see if it works: https://github.com/horshack-dpreview/setPL/pull/3

**Comment by horshack-dpreview** [comment]
> Hello there,
> 
> thank you for this nice script! I have fiddled around a bit, to implement a read-only mode on my end and have come across what seems like a bug. The script uses a variable called INTEL_PL1_ENABLE_BITS_HIGH in [line 252](https://github.com/horshack-dpreview/setPL/blob/0713c5ca18a44fe91971f3ff5071f220a0d91b91/setPL.sh#L252) but this variable is never set. My guess is that this was supposed to be INTEL_**PL2**_ENABLE_BITS_HIGH which is set alongside INTEL_PL1_ENABLE_BITS_LOW early in the script.

Nice catch, thanks! I've committed the fix for this. Fortunately it only affects the reporting and only for the MMIO already-locked case.
