### ISSUE TITLE
Will This script overwrite BIOS settings?

### ISSUE THREAD

**Issue by cesur98** [horshack-dpreview/setPL#6]
I'm an i5-12500H user(Which is not supported by Intel Extreme Tuning Utility). My Cpu was getting hot and I didn't want to disable Turbo Boost. So I tried to decrease PL1 and PL2 Turbo boost settings via XTU for better Temperatures. Now my CPU is unlocked and PL1 is set as default to 95w(Should be 45W) and PL2 set as default to 115w(Should be 95w) by Intel XTU.

I tried to delete XTU, reinstall Windows, loaded default settings in BIOS, and updated BIOS to a newer version to fix this issue but none of these fixed my issue. My CPU is constantly hitting 100C on idle and I can't change these settings. Other CPU tuning applications only apply Turbo Boost settings to Windows. But I need to overwrite Intel XTU's default settings. Can I use your script to fix my problem?

**Comment by horshack-dpreview** [comment]
Sorry for the late reply. This script is for Linux only so it wont address your Windows issues.
